spring.application.name=validator

# Dirección del broker de Kafka
spring.kafka.bootstrap-servers=${KAFKA_BOOTSTRAP_SERVERS:localhost:29092}
server.port=8089

# Configuración del consumer
spring.kafka.consumer.group-id=order-validator-group2
spring.kafka.consumer.auto-offset-reset=earliest
spring.kafka.consumer.key-deserializer=org.apache.kafka.common.serialization.StringDeserializer
spring.kafka.consumer.value-deserializer=org.springframework.kafka.support.serializer.JsonDeserializer

# Permitir deserializar cualquier paquete (para DTOs)
spring.kafka.consumer.properties.spring.json.trusted.packages=*

# Configuración del producer
spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=org.springframework.kafka.support.serializer.JsonSerializer

spring.kafka.consumer.properties.spring.json.value.default.type=com.soa.tp1.order.validator.DTO.OrderCreated
