services:
  broker:
    image: apache/kafka:latest #imagen oficial de kafka
    container_name: kafka-broker
    ports:
      - "${KAFKA_PORT:-9092}:9092" #mapeo el puerto 9092
      - "${KAFKA_EXTERNAL_PORT:-29092}:29092" #mapeo el puerto 29092
    environment:
      KAFKA_NODE_ID: ${KAFKA_NODE_ID:-1}
      #Esto es para KRaft, actúa como broker y contolador, sin  necesidad de zookeeper (un proceso que se usaba antes para coordinar los brokers, pero ahora con KRaft ya no es necesario)
      KAFKA_PROCESS_ROLES: broker,controller
      #Acá escucha en 2 puertos, uno para los clientes spring boot y kafka-ui (9092) y otro para la comunicación entre controladores (9093)
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092,PLAINTEXT_HOST://0.0.0.0:${KAFKA_EXTERNAL_PORT:-29092},CONTROLLER://0.0.0.0:9093      
      #Lo que kafka le dice a los clientes para que se conecten, en este caso localhost:9092, pero dentro de la red de docker se conecta a broker:9092
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://broker:9092,PLAINTEXT_HOST://localhost:${KAFKA_EXTERNAL_PORT:-29092}
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_CONTROLLER_QUORUM_VOTERS: ${KAFKA_NODE_ID:-1}@broker:9093
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: ${KAFKA_REPLICATION_FACTOR:-1}
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: ${KAFKA_REPLICATION_FACTOR:-1}
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
      KAFKA_LOG_RETENTION_HOURS: ${KAFKA_RETENTION_HOURS:-168}  # NO usamos base de datos, si no que se usan los kafka logs con una persistencia que yo seteo como 7 dias
      KAFKA_NUM_PARTITIONS: ${KAFKA_PARTITIONS:-3} #3 particiones, como se recomienda en el TP
      CLUSTER_ID: ${KAFKA_CLUSTER_ID:-MkU3OEVBNTcwNTJENDM2Qk}
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: 'true' #Para que se creen automáticamente los topics cuando se publiquen mensajes
    volumes: #Para persistir los datos de kafka, si no se borra todo cada vez que se levanta el contenedor
      - kafka_data:/var/lib/kafka/data
    healthcheck:
      test: ["CMD-SHELL", "/opt/kafka/bin/kafka-broker-api-versions.sh --bootstrap-server localhost:9092 || exit 1"]
      interval: 15s
      timeout: 10s
      retries: 10
      start_period: 30s

#Este servicio se ejecuta 1 sola vez y termina
  init-topics:
    image: apache/kafka:latest #misma imagen q el broker
    container_name: init-topics
    depends_on:
      broker:
        condition: service_healthy
    environment:
      KAFKA_BOOTSTRAP_SERVERS: broker:9092
    # Acá creo los topics necesarios para el TP, con el número de particiones y factor de replicación que se setea en el .env o por defecto 3 particiones y replicación 1
    #El topic 1 es el que se publica desde el microservicio de ordenes, el topic 2 es el que se consume desde el microservicio de validación y el topic 3 es la DLQ (Dead Letter Queue) para los mensajes que no se pudieron procesar correctamente en el microservicio de validación
    command: |
      bash -c " sleep 5 &&
        /opt/kafka/bin/kafka-topics.sh --create --if-not-exists --topic orders.created.v1 --bootstrap-server broker:9092 --partitions ${KAFKA_PARTITIONS:-3} --replication-factor ${KAFKA_REPLICATION_FACTOR:-1} &&
        /opt/kafka/bin/kafka-topics.sh --create --if-not-exists --topic orders.validated.v1 --bootstrap-server broker:9092 --partitions ${KAFKA_PARTITIONS:-3} --replication-factor ${KAFKA_REPLICATION_FACTOR:-1} &&
        /opt/kafka/bin/kafka-topics.sh --create --if-not-exists --topic orders.validation.dlq.v1 --bootstrap-server broker:9092 --partitions ${KAFKA_PARTITIONS:-3} --replication-factor ${KAFKA_REPLICATION_FACTOR:-1} &&
        echo 'Topics creados: orders.created.v1, orders.validated.v1, orders.validation.dlq.v1' &&
        /opt/kafka/bin/kafka-topics.sh --list --bootstrap-server broker:9092
      "

  kafka-ui: #a esto lo vemos en localhost:8080
    image: provectuslabs/kafka-ui:latest
    container_name: kafka-ui
    ports:
      - "${KAFKA_UI_PORT:-8080}:8080"
    environment:
      KAFKA_CLUSTERS_0_NAME: local
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: broker:9092 #conecta al broker por nombre
      # Para ver desde host
      KAFKA_CLUSTERS_0_ADVERTISED_LISTENERS: localhost:${KAFKA_PORT:-9092}
    #espera broker listo y topics creados
    depends_on:
      - broker
      - init-topics

  order-audit:
    image: twbenjaminvargas/order-audit:1.1.0
    container_name: order-audit
    ports:
      - "8083:8080"
    environment:
      KAFKA_SERVERS: broker:9092
      APP_KAFKA_CONSUMER_TOPIC: orders.validated.v1
      GROUP_ID: order-audit-group
    depends_on:
      - broker

  order-validator:
    image: antobadami845/order-validator:2.0  # imagen de Docker Hub
    container_name: order-validator
    ports:
      - "8082:8082"
    environment:
      KAFKA_BOOTSTRAP_SERVERS: broker:9092
    depends_on:
      - broker

  order-api:
    image: lbiondi733/order-api:3.0  # imagen de Docker Hub
    container_name: order-api
    ports:
      - "8081:8081"
    environment:
      SPRING_KAFKA_BOOTSTRAP_SERVERS: broker:9092
    depends_on:
      broker:
        condition: service_healthy

  order-notifications:
    image: aggostinaperez/order-notifications:5.0
    container_name: order-notifications
    ports:
      - "8084:8084"
    environment:
      KAFKA_BOOTSTRAP_SERVERS: broker:9092
    depends_on:
      broker:
        condition: service_healthy
      
volumes:
  kafka_data:
    driver: local
