server.port=8084
# se conecta al broker de kafka
spring.kafka.bootstrap-servers=broker:29092
#consumer group para usar el fan out
spring.kafka.consumer.group-id=notification-group
#Si el consumer arranca sin offset guardado, empieza desde el mensaje más viejo.
#esto sirve para la prueba de apagar el consumer, enviar mensajes al topic, y luego volver a prender el consumer para que procese los mensajes enviados mientras estaba apagado.
spring.kafka.consumer.auto-offset-reset=earliest
# La key del mensaje se interpreta como String.
spring.kafka.consumer.key-deserializer=org.apache.kafka.common.serialization.StringDeserializer
# El mensaje Kafka viene en JSON y se convierte automáticamente al objeto OrderValidated
spring.kafka.consumer.value-deserializer=org.springframework.kafka.support.serializer.JsonDeserializer

spring.kafka.consumer.properties.spring.json.trusted.packages=*

management.endpoints.web.exposure.include=health
management.endpoint.health.show-details=always